# Generated by Django 4.2.24 on 2025-09-16 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_profile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='branch_name',
        ),
        migrations.AlterField(
            model_name='department',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.branch'),
        ),
        migrations.AlterField(
            model_name='role',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.branch'),
        ),
    ]
