# Generated by Django 4.2.24 on 2025-09-30 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import purchase.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_candidatedocument_alter_candidate_aadhar_number_and_more'),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SRN_ID', models.CharField(editable=False, max_length=20, unique=True)),
                ('received_date', models.DateField()),
                ('return_date', models.DateField(default=purchase.models.get_default_srn_date)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Partially Returned', 'Partially Returned'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20)),
                ('original_purchased_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('global_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('return_subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('global_discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('rounding_adjustment', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amount_to_recover', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('GRN_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.stockreceipt')),
                ('PO_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.purchaseorder')),
                ('return_initiated_by', models.ForeignKey(blank=True, limit_choices_to={'department__department_name': 'Sales'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.supplier')),
            ],
        ),
        migrations.AddField(
            model_name='stockreceiptitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='stockreceiptitem',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='stockreceiptitem',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='stockreceiptitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='StockReturnRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('stock_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='purchase.stockreturn')),
            ],
        ),
        migrations.CreateModel(
            name='StockReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uom', models.CharField(blank=True, max_length=50)),
                ('qty_ordered', models.IntegerField(blank=True, null=True)),
                ('qty_rejected', models.IntegerField(blank=True, null=True)),
                ('qty_returned', models.IntegerField()),
                ('return_reason', models.TextField(blank=True)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product')),
                ('stock_receipt_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.stockreceiptitem')),
                ('stock_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase.stockreturn')),
            ],
        ),
        migrations.CreateModel(
            name='StockReturnAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='stock_return_attachments/')),
                ('stock_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='purchase.stockreturn')),
            ],
        ),
        migrations.CreateModel(
            name='SerialNumberReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=50)),
                ('stock_return_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serial_numbers', to='purchase.stockreturnitem')),
            ],
        ),
    ]
