# Generated by Django 4.2.24 on 2025-10-07 12:21

import crm.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_stockreturn_stockreceiptitem_discount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_candidatedocument_alter_candidate_aadhar_number_and_more'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryNoteReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DNR_ID', models.CharField(default=crm.models.generate_delivery_note_return_id, editable=False, max_length=20, unique=True)),
                ('dnr_date', models.DateField(default=django.utils.timezone.now)),
                ('customer_reference_no', models.CharField(blank=True, max_length=50)),
                ('email_id', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryNoteReturnAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='delivery_note_return_attachments/')),
                ('delivery_note_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='crm.deliverynotereturn')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryNoteReturnComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivery_note_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='crm.deliverynotereturn')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryNoteReturnHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivery_note_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='crm.deliverynotereturn')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryNoteReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uom', models.CharField(blank=True, max_length=50)),
                ('invoiced_qty', models.IntegerField(default=0)),
                ('returned_qty', models.IntegerField(default=0)),
                ('return_reason', models.TextField(blank=True)),
                ('delivery_note_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.deliverynotereturn')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product')),
                ('serial_numbers', models.ManyToManyField(blank=True, to='purchase.serialnumber')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryNoteReturnRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('delivery_note_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='crm.deliverynotereturn')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('INVOICE_RETURN_ID', models.CharField(default=crm.models.generate_invoice_return_id, editable=False, max_length=20, unique=True)),
                ('invoice_return_date', models.DateField(default=django.utils.timezone.now)),
                ('customer_reference_no', models.CharField(blank=True, max_length=50)),
                ('email_id', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customer')),
                ('sales_order_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.salesorder')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceReturnAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='invoice_return_attachments/')),
                ('invoice_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='crm.invoicereturn')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceReturnComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('invoice_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='crm.invoicereturn')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceReturnHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('invoice_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='crm.invoicereturn')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uom', models.CharField(blank=True, max_length=50)),
                ('invoiced_qty', models.IntegerField(default=0)),
                ('returned_qty', models.IntegerField(default=0)),
                ('return_reason', models.TextField(blank=True)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('invoice_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.invoicereturn')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product')),
                ('serial_numbers', models.ManyToManyField(blank=True, to='purchase.serialnumber')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceReturnRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('invoice_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='crm.invoicereturn')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceReturnSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_grand_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('global_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('return_subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('global_discount_amount', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('rounding_adjustment', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amount_to_refund', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('invoice_return', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='crm.invoicereturn')),
            ],
        ),
        migrations.RemoveField(
            model_name='drn_attachment',
            name='drn',
        ),
        migrations.RemoveField(
            model_name='drn_comment',
            name='drn',
        ),
        migrations.RemoveField(
            model_name='drn_history',
            name='drn',
        ),
        migrations.RemoveField(
            model_name='drn_lineitem',
            name='drn',
        ),
        migrations.RemoveField(
            model_name='drn_lineitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='number',
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='DN_ID',
            field=models.CharField(default=crm.models.generate_dn_id, editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='INVOICE_ID',
            field=models.CharField(default=crm.models.generate_invoice_id, editable=False, max_length=20, unique=True),
        ),
        migrations.DeleteModel(
            name='DeliveryReturnNote',
        ),
        migrations.DeleteModel(
            name='Drn_Attachment',
        ),
        migrations.DeleteModel(
            name='Drn_Comment',
        ),
        migrations.DeleteModel(
            name='Drn_History',
        ),
        migrations.DeleteModel(
            name='Drn_LineItem',
        ),
        migrations.AddField(
            model_name='deliverynotereturn',
            name='invoice_return_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.invoicereturn'),
        ),
    ]
